### PR TITLE
Add BSD 3 License to repository

### PR DESCRIPTION
**Pull request by mark-nicol**

### CODE REVIEW

**Comment by flyingfrog81** [comment]
Shall we rename this repo to someting more significant?

**Comment by mark-nicol** [comment]
Happy to rename - It was a purely descriptive name at the time. I can ask the team, or do you have any suggestions for a more significant name.

**Comment by mark-nicol** [comment]
Would 'ska-engineering-ui-compose-utils' be acceptable?

**Comment by flyingfrog81** [comment]
Yes , certainly more explanatory

**Comment by flyingfrog81** [comment]
Merging this branch into the master now. Feel free to rename it afterwards.

**Review by flyingfrog81 — APPROVED** [review]

**Comment by mark-nicol** [comment]
Hi Marco - Since transferring across I no longer seem to have admin rights for this repo, so I don't think I can do the rename. Happy if you want to do it and I'll do a pull request for tidying up the readme and any other references.

**Comment by flyingfrog81** [comment]
oh you're right. I have now renamed the repo.

**Pull request merged**
